config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'
  resources :posts

  namespace :admin do
    root to: 'dashboard#index'
    resources :posts
  end

  namespace :profiles do
    root to: 'profiles#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :posts_tags
  has_many :tags, through: :posts_tags
  has_one_attached :picture

  validates :title, presence: true
  accepts_nested_attributes_for :tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_one :profile

  after_create :link_profile

  private

  def link_profile
    Profile.create!(user_id: id, description: 'Ma description')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css' %>
  <%= stylesheet_link_tag 'application', 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <nav class="navbar">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">Application</a>
        <span class="navbar-burger burger" data-target="navbarMenu">
          <span></span>
        </span>
      </div>
      <div id="navbarMenu" class="navbar-menu">
        <div class="navbar-end">
          <a href="/" class="navbar-item is-active">
            Accueil
          </a>
          <a href="<%= admin_root_path %>" class="navbar-item">
            Administration
          </a>
          <div class="navbar-item has-dropdown is-hoverable">
            <% if current_user %>
              <a class="navbar-link">
                <i class="fa fa-user-circle"></i> <%= current_user.name %>
              </a>
              <div class="navbar-dropdown">
                <a class="navbar-item">
                  Profil
                </a>
                <hr class="navbar-divider">
                <%= link_to('Se déconnecter', destroy_user_session_path, method: :delete, class: 'navbar-item') %>
              </div>
            <% else %>
              <a class="navbar-link">
                <i class="fa fa-user-circle"></i> Mon compte
              </a>
              <div class="navbar-dropdown">
                <a href="<%= new_user_session_path %>" class="navbar-item">Connexion</a>
                <a href="<%= new_user_registration_path %>" class="navbar-item">Créer un compte</a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="section">
      <%= yield %>
    </div>
  </div>

  <footer class="footer">
    <div class="container">
      <div class="content has-text-centered">
        <div class="soc">
          <a href="#"><i class="fa fa-github-alt fa-2x" aria-hidden="true"></i></a>
          <a href="#"><i class="fa fa-youtube fa-2x" aria-hidden="true"></i></a>
          <a href="#"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a>
          <a href="#"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></a>
        </div>
        <p>
          <strong>Bulma</strong> by <a href="http://jgthms.com">Jeremy Thomas</a>.
          The source code is licensed <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. <br>
        </p>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/posts/index.html.erb
<!--<div class="box">
  <div class="field has-addons">
    <div class="control is-expanded">
      <input class="input has-text-centered" type="search" placeholder="Entrez votre recherche">
    </div>
    <div class="control">
      <a class="button is-info">Rechercher</a>
    </div>
  </div>
</div>-->

<div class="row columns">

<% @posts.each do |post| %>

    <div class="column is-one-third">
      <a href="<%= post_path(post.id) %>">
        <div class="card large">
          <% if post.picture.attached? %>
            <div class="card-image">
              <figure class="image">
                <img src="<%= url_for post.picture %>" alt="Image">
              </figure>
            </div>
          <% end %>
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-75x75">
                  <img class="is-rounded" src="https://www.drupal.org/files/issues/default-avatar.png" alt="Image">
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4 no-padding"><%= post.title %></p>
                <p><span class="title is-6"><%= post.user.name %></span></p>
                <p class="subtitle is-6"><%= post.created_at %></p>
              </div>
            </div>
          </div>
        </div>
      </a>
    </div>

<% end %>

</div>

app/views/posts/show.html.erb
<div class="post-title">
  <h2><%= @post.title %></h2>
  <p>Catégorie : <b><%= @post.category.name %></b></p>
  <i>Par <%= @post.user.name %> le <%= @post.created_at %> (dernière édition <%= @post.updated_at %>)</i>
</div>

<p><%= @post.content %></p>